version: '3'

services:

  hive:
    image: hive
    hostname: hive
    build:
      context: ./hive
      args:
        HIVE_VER: 3.1.1
    volumes:
      - "./hive/hive-site.xml:/usr/local/apache/hive/conf/hive-site.xml"
      - "./hive/format.sh:/usr/local/bin/format.sh"
      - "./hive/start.sh:/usr/local/bin/start.sh"
      - "../data/hive:/usr/local/apache/hive/data"
      - "../logs/hive:/usr/local/apache/hive/logs"
    command: start.sh
    
  lab:
    image: jupyter/base-notebook
    volumes:
     - ./lab/:/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks
  
  sqoop:
    image: sqoop
    hostname: sqoop
    build:
      context: ./sqoop
      args:
        SQOOP_VER: 1.99.7
        PG_DRIVER: 42.2.5
    volumes:
      - "./sqoop/format.sh:/tmp/format.sh"
      - "./sqoop/start.sh:/tmp/start_sqoop.sh"
      - "./sqoop/sqoop.properties:/usr/local/apache/sqoop/conf/sqoop.properties"
    command: ./start_sqoop.sh

  postgres:
    image: postgres:9.4.20-alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=sqoop
      - POSTGRES_USER=sqoop
      - POSTGRES_DB=sqoop
    volumes:
      - "./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql"

networks:
  default:
    external:
      name: hadoop
      
volumes:
  portainer_data: