version: '3'

services:
  hive:
    image: hive
    hostname: namenode
    build:
      context: ./hive
      args:
        HIVE_VER: 3.1.1
    volumes:
      - "./hive/format.sh:/tmp/format.sh"
      - "./hive/start.sh:/tmp/start_hive.sh"
    command: ./start_hive.sh
    
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  lab:
    image: jupyter/base-notebook
    volumes:
     - ./lab/:/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

networks:
  default:
    external:
      name: hadoop
      
volumes:
  portainer_data: